# Generated by Django 5.0.4 on 2024-08-10 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0003_alter_service_content_passwordchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
    ]
