# Generated by Django 5.0.4 on 2025-03-03 17:02

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('marks', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('speciality', models.CharField(default='', max_length=255)),
                ('service_cost', models.IntegerField(blank=True, null=True)),
                ('aboutme', models.CharField(default='', max_length=650)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='authentication.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorPasswordChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorProfileInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('marks', models.CharField(blank=True, max_length=100, null=True)),
                ('work_history_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('work_start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('work_end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.CharField(blank=True, max_length=255, null=True)),
                ('specializations', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace_image', models.ImageField(blank=True, null=True, upload_to='workspace_images/')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_info', to='authentication.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_available', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='authentication.instructorprofile')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('instructor', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
