# Generated by Django 5.0.4 on 2024-08-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_instructorprofile_service'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
