# Generated by Django 5.0.4 on 2024-08-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='speciality',
            field=models.CharField(default='', max_length=255),
        ),
    ]
