# Generated by Django 5.0.4 on 2024-08-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_education_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='maxcost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='minicost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
