# Generated by Django 5.0.4 on 2024-08-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_education_maxcost_education_minicost'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='aboutme',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='perhpur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
