# Generated by Django 5.0.4 on 2024-08-29 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_gender'),
        ('instructors', '0007_education_aboutme_education_perhpur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='aboutme',
            field=models.CharField(default='', max_length=650),
        ),
        migrations.CreateModel(
            name='InstructorProfileInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('marks', models.CharField(blank=True, max_length=100, null=True)),
                ('work_history_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('work_start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('work_end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.CharField(blank=True, max_length=255, null=True)),
                ('specializations', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace_image', models.ImageField(blank=True, null=True, upload_to='workspace_images/')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_info', to='authentication.instructorprofile')),
            ],
        ),
    ]
