# Generated by Django 5.0.4 on 2024-10-29 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0009_availabletimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletimeslot',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
