# Generated by Django 5.0.4 on 2024-10-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0010_availabletimeslot_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='maxcost',
            new_name='service_cost',
        ),
        migrations.RemoveField(
            model_name='education',
            name='minicost',
        ),
        migrations.RemoveField(
            model_name='education',
            name='perhpur',
        ),
    ]
